### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by elax46** [TBens/lovelace-ui-minimalist#3]
strange configuration error!

`Invalid config for [frontend]: expected a dictionary for dictionary value @ data['frontend']['themes']['accent-color']. Got 'var(--google-yellow)'
expected a dictionary for dictionary value @ data['frontend']['themes']['app-header-background-color']. Got 'var(--primary-background-color)'
expected a dictionary for dictionary value @ data['frontend']['themes']['app-header-text-color']. Got 'var(--primary-text-color)'
expected a dictionary for dictionary value @ data['frontend']['themes']['border-radius']. Got '20px'
expected a dictionary for dictionary value @ data['frontend']['themes']['box-shadow']. Got '0px 2px 4px 0px rgba(0,0,0,0.16)'
expected a dictionary for dictionary value @ data['frontend']['themes']['card-background-color']. Got '#FAFAFA'
expected a dictionary for dictionary value @ data['frontend']['themes']['card-mod-root']. Got 'app-toolbar {\n display: none;\n}\n'
expected a dictionary for dictionary value @ data['frontend']['themes']['card-mod-theme']. Got 'mobile'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-background-blue']. Got '250, 250, 250'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-background-green']. Got '250, 250, 250'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-background-red']. Got '250, 250, 250'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-background-yellow']. Got '250, 250, 250'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-blue']. Got '61, 90, 254'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-blue-text']. Got 'var(--primary-text-color)'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-green']. Got '1, 200, 82'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-green-text']. Got 'var(--primary-text-color)'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-grey']. Got '187, 187, 187'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-pink']. Got '233, 30, 99'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-purple']. Got '102, 31, 255'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-red']. Got '245, 68, 54'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-red-text']. Got 'var(--primary-text-color)'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-theme']. Got '51,51,51'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-yellow']. Got '255, 145, 1'
expected a dictionary for dictionary value @ data['frontend']['themes']['color-yellow-text']. Got 'var(--primary-text-color)'
expected a dictionary for dictionary value @ data['frontend']['themes']['divider-color']. Got 'rgba(var(--color-theme),.12)'
expected a dictionary for dictionary value @ data['frontend']['themes']['error-color']. Got 'var(--google-red)'
expected a dictionary for dictionary value @ data['frontend']['themes']['google-blue']. Got '#3D5AFE'
expected a dictionary for dictionary value @ data['frontend']['themes']['google-green']. Got '#01C852'
expected a dictionary for dictionary value @ data['frontend']['themes']['google-grey']. Got '#BBBBBB'
expected a dictionary for dictionary value @ data['frontend']['themes']['google-red']. Got '#F54436'
expected a dictionary for dictionary value @ data['frontend']['themes']['google-violet']. Got '#661FFF'
expected a dictionary for dictionary value @ data['frontend']['themes']['google-yellow']. Got '#FF9101'
expected a dictionary for dictionary value @ data['frontend']['themes']['ha-card-box-shadow']. Got 'var(--box-shadow)'
expected a dictionary for dictionary value @ data['frontend']['themes']['info-color']. Got 'var(--google-blue)'
expected a dictionary for dictionary value @ data['frontend']['themes']['mdc-theme-on-secondary']. Got 'var(--card-background-color)'
expected a dictionary for dictionary value @ data['frontend']['themes']['mini-media-player-accent-color']. Got 'var(--google-red)'
expected a dictionary for dictionary value @ data['frontend']['themes']['opacity-bg']. Got '1'
expected a dictionary for dictionary value @ data['frontend']['themes']['paper-tabs-selection-bar-color']. Got 'var(--primary-text-color)'
expected a dictionary for dictionary value @ data['frontend']['themes']['primary-background-color']. Got '#EFEFEF'
expected a dictionary for dictionary value @ data['frontend']['themes']['primary-color']. Got '#434343'
expected a dictionary for dictionary value @ data['frontend']['themes']['primary-text-color']. Got '#212121'
expected a dictionary for dictionary value @ data['frontend']['themes']['secondary-background-color']. Got '#EFEFEF'
expected a dictionary for dictionary value @ data['frontend']['themes']['sidebar-selected-icon-color']. Got 'var(--google-red)'
expected a dictionary for dictionary value @ data['frontend']['themes']['sidebar-selected-text-color']. Got 'var(--google-red)'
expected a dictionary for dictionary value @ data['frontend']['themes']['sidebar-text-color']. Got '#80868b'
expected a dictionary for dictionary value @ data['frontend']['themes']['slider-bar-color']. Got 'rgba(var(--color-blue),0.38)'
expected a dictionary for dictionary value @ data['frontend']['themes']['slider-color']. Got 'rgb(var(--color-blue))'
expected a dictionary for dictionary value @ data['frontend']['themes']['state-icon-color']. Got 'rgb(var(--color-theme))'
expected a dictionary for dictionary value @ data['frontend']['themes']['success-color']. Got 'var(--google-green)'
expected a dictionary for dictionary value @ data['frontend']['themes']['switch-checked-color']. Got 'var(--google-blue)'
expected a dictionary for dictionary value @ data['frontend']['themes']['warning-color']. Got 'var(--google-yellow)'
value should be a string for dictionary value @ data['frontend']['themes']['modes']['dark']. Got OrderedDict([('primary-text-color', '#DDDDDD'), ('primary-color', '#89B3F8'), ('google-red', '#F18B82'), ('google-green', '#80C994'), ('google-yellow', '#FCD663'), ('google-blue', '#89B3F8'), ('google-violet', '#BB86FC'), ('google-grey', '#BBBBBB'), ('color-red', '241, 139, 130'), ('color-green', '128, 201, 148'), ('color-yellow', '252, 214, 99'), ('color-blue', '137, 179, 248'), ('color-theme', '221,221,221'), ('color-purple', '102, 31, 255'), ('color-grey', '187, 187, 187'), ('color-pink', ...
value should be a string for dictionary value @ data['frontend']['themes']['modes']['light']. Got OrderedDict([('primary-text-color', '#212121'), ('primary-color', '#434343'), ('google-red', '#F54436'), ('google-green', '#01C852'), ('google-yellow', '#FF9101'), ('google-blue', '#3D5AFE'), ('google-violet', '#661FFF'), ('google-grey', '#BBBBBB'), ('color-red', '245, 68, 54'), ('color-green', '1, 200, 82'), ('color-yellow', '255, 145, 1'), ('color-blue', '61, 90, 254'), ('color-purple', '102, 31, 255'), ('color-grey', '187, 187, 187'), ('color-pink', '233, 30, 99'), ('color-theme', '51,51,5.... (See /config/configuration.yaml, line 24).
Component error: themes - Integration 'themes' not found.
Component error: mode - Integration 'mode' not found.
Component error: resources - Integration 'resources' not found.`

**Comment by mbillow** [comment]
`data['frontend']['themes']` is meant to be a dictionary with theme names as keys and theme definition dictionaries as values. It looks like however you are loading/including the theme YAML, you are doing it incorrectly, since it is finding the actual theme definition. For example, `data['frontend']['themes']['accent-color']` should actually be `data['frontend']['themes']['desktop']['accent-color']`. Double check how you are including the theme YAML.

**Comment by elax46** [comment]
Thanks for your answer anyway I have already solved it.
