### ISSUE TITLE
[Info Request] - Config of Presence Sensors

### ISSUE THREAD

**Issue by ee02217** [TBens/lovelace-ui-minimalist#9]
Hi,

I love the work you shared here.
Can you please share your configuration of the below sensors?
```
sensor.present
sensor.absent
sensor.travail
```

Sharing the config of one of them would be enough.

**Comment by TBens** [comment]
Hi 👋
I have already shared my configuration on the forum, you will find the post here :
https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/280

**Comment by ee02217** [comment]
Ahhh man... it's the history state one.

Got it! Really sorry :)

Great work!
